language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - ./travis.sh

env:
  matrix:
    - RUN_ITS=false
    - RUN_ITS=true SQ_VERSION=LTS
    - RUN_ITS=true SQ_VERSION=DEV

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
