language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - ./travis.sh

env:
  - TARGET=CI
  - TARGET=IT SQ_VERSION=LTS
  - TARGET=IT SQ_VERSION=DEV

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    # analysis and integration tests
    - $HOME/.sonar

notifications:
  email: false
